#!/usr/bin/env lua
package.path = package.path
	.. ";./?.lua;./?/init.lua;"
	.. os.getenv("HOME")
	.. "/.config/sketchybar/?.lua;"
	.. os.getenv("HOME")
	.. "/.config/sketchybar/?/init.lua"
--sketchybar --add event aerospace_workspace_change

--for sid in $(aerospace list-workspaces --all); do
--    sketchybar --add item space.$sid left \
--        --subscribe space.$sid aerospace_workspace_change \
--        --set space.$sid \
--        background.color=0x44ffffff \
--        background.corner_radius=5 \
--        background.height=20 \
--        background.drawing=off \
--        label="$sid" \
--        click_script="aerospace workspace $sid" \
--        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
--done

-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")
